### ISSUE TITLE
Refactor models and repos.

### ISSUE THREAD

**Issue by trtstm** [micado-eu/backend#11]
Extract the generic code for the translation flow out of the models into a base model. Same for the repos.

**Comment by gioppoluca** [comment]
Are you aware that the code of the models and repos is autogenerated by loopback?
Just mind not to waste time in changing that part.

**Comment by trtstm** [comment]
Yes, but I would like to move the logic that updates the models translation status into a mixin that can be shared by all repos (https://loopback.io/doc/en/lb4/migration-models-mixins.html#loopback-4-approach-1).

For example now I added code to the TopicTranslationRepository that can update the translation status of a topic. This code is quite generic except for the table name and the name of the column that contains the string that has to be translated. So I would like to move that code out to a mixin and then all repos use that mixin.

The query in https://github.com/micado-eu/backend/blob/85f56818a14b7c2a725e4767ea88897eefef4c1d/application/micado-backend/src/repositories/topic-translation.repository.ts#L54 could then become
`const q = 'UPDATE ' + this.getTableName() + ' SET "translationState" = 2 WHERE "translationState" = 1 AND "id" in ( ' + ids.join(',') + ' );';`
All repositories that want to support translations should then just implement the method getTableName.
