### ISSUE TITLE
Add date to ratings table

### ISSUE THREAD

**Issue by gioppoluca** [micado-eu/backend#17]

**Comment by gioppoluca** [comment]
Puoi aggiungere un campo data ai rating?
Inoltre occorre modificare il backent
Nel campo mettilo in modo che di default assegni la data corrente e che non sia obbligatorio nel backend

**Comment by gioppoluca** [comment]
my_date date not null default CURRENT_DATE
To set default

**Comment by GiuseppeCSI** [comment]
Done
