### ISSUE TITLE
Disparity in published column between entities and db

### ISSUE THREAD

**Issue by ivchicano** [micado-eu/backend#18]
In the model entities the published field is in the entities itself, while in the db the column is in the translation tables.
Is this intended?
Asking @GiuseppeCSI because he made the changes

**Comment by GiuseppeCSI** [comment]
We re-added the published column on the entities, so now there should be a published column both on the entity and the entity_translation. If you see this disparity on your local instance of the db, delete it and recreate it, we added the changes a couple of days ago

**Comment by ivchicano** [comment]
Understood, closed
