### ISSUE TITLE
Error 500 in images controller Permission Denied

### ISSUE THREAD

**Issue by ivchicano** [micado-eu/backend#19]
The shared directory /images doesn't have permissions to save or read the images
Permissions should be added to the directory (chown user node) in the Dockerfile https://hub.docker.com/r/micadoproject/backend/dockerfile
```
Unhandled error in POST /upload-image: 500 Error: EACCES: permission denied, open '/images/0505fa4f2c45519033fcf179a5ac4c0d'
```

**Comment by ivchicano** [comment]
Seems like the list-images endpoint wasn't finding the volume, fixed in https://github.com/micado-eu/backend/commit/619185526405b8f6bf419de01a54b45e2b75d957
Still trying to find a fix to the uploading permission denied

**Comment by gioppoluca** [comment]
strange this does not happens in my development environment

**Comment by gioppoluca** [comment]
how can I replicate the error in shared dev environment?

**Comment by ivchicano** [comment]
Using postman, POST request to https://api.micadoproject.eu/backend/1.0.0/upload-image with body being a form-data file with the file attached as value
![Postman_nT4ZVwUEe6](https://user-images.githubusercontent.com/46921761/101766113-99114d80-3ae2-11eb-889f-c69a14f1f2a4.png)

**Comment by gioppoluca** [comment]
Fixed we need to remember that the shated_images folder have to have 777 permission (the backend writes to it and nginx mount it only in read mode so no security risk)
